### ISSUE TITLE
Unable to use it with Next 14

### ISSUE THREAD

**Issue by wilmerterrero** [PuruVJ/neoconfetti#21]
I tried to use it with "use client" but didn't work.

**Comment by PuruVJ** [comment]
Hi, can you tell what the error is?

**Comment by wilmerterrero** [comment]
> Hi, can you tell what the error is?

I just no work hahaha

**Comment by lgraubner** [comment]
The `use client` directive is needed as this package uses client component features (`useRef` in this case).

You can read more about it here: https://react.dev/reference/rsc/use-client

This can also be solved from the user side by wrapping it in a component and add `use client` there. But probably makes sense to add it :)

**Comment by PuruVJ** [comment]
Released in @neoconfetti/react v1.0.0. Let me know if it worked

**Comment by lgraubner** [comment]
Works as expected. Thanks for merging the PR :)
